config/routes.rb
Rails.application.routes.draw do
  resources :tarefas
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => "tarefas#index"

  get '/tarefas/finalizar/:id', action: :finalizar, controller: 'tarefas'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tarefa.rb
class Tarefa < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!

    def after_sign_out_path_for(resource_or_scope)
        root_path
    end
end

app/controllers/tarefas_controller.rb
class TarefasController < ApplicationController
  before_action :set_tarefa, only: [:show, :edit, :update, :destroy]

  def finalizar
    @tarefa = Tarefa.find(params[:id])
    data_atual = DateTime.now
    
    respond_to do |format|
      if @tarefa.update(:finalizado => true, :data_finalizado => data_atual.strftime("%Y-%m-%d"))
        format.html { redirect_to action: "index" }
      end
    end
    
  end
  # GET /tarefas
  # GET /tarefas.json
  def index
    data_atual = DateTime.now

    @tarefas_finalizadas = Tarefa.where(user_id: current_user.id, finalizado: true)
    @tarefas_em_andamento = Tarefa.where("prazo >= '#{data_atual.strftime("%Y-%m-%d")}' and finalizado = false")
    @tarefas_em_atraso = Tarefa.where("prazo < '#{data_atual.strftime("%Y-%m-%d")}' and finalizado = false")
  end

  # GET /tarefas/1
  # GET /tarefas/1.json
  def show
  end

  # GET /tarefas/new
  def new
    @tarefa = Tarefa.new 
  end

  # GET /tarefas/1/edit
  def edit
  end

  # POST /tarefas
  # POST /tarefas.json
  def create
    
    @tarefa = Tarefa.new
    @tarefa.titulo = tarefa_params["titulo"]
    @tarefa.descricao = tarefa_params["descricao"]
    @tarefa.prazo =  params["tarefa"]["prazo"]
    @tarefa.user_id = current_user.id

    respond_to do |format|
      if @tarefa.save
        format.html { redirect_to @tarefa, notice: 'Tarefa was successfully created.' }
        format.json { render :show, status: :created, location: @tarefa }
      else
        format.html { render :new }
        format.json { render json: @tarefa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tarefas/1
  # PATCH/PUT /tarefas/1.json
  def update
    @tarefa = Tarefa.find(params[:id])
    titulo = params[:tarefa][:titulo]
    descricao = params[:tarefa][:descricao]
    prazo = params[:tarefa][:prazo]

    respond_to do |format|
      if @tarefa.update(:titulo => titulo, :descricao => descricao, :prazo => prazo)
        format.html { redirect_to @tarefa, notice: 'Tarefa was successfully updated.' }
        format.json { render :show, status: :ok, location: @tarefa }
      else
        format.html { render :edit }
        format.json { render json: @tarefa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tarefas/1
  # DELETE /tarefas/1.json
  def destroy
    @tarefa.destroy
    respond_to do |format|
      format.html { redirect_to tarefas_url, notice: 'Tarefa was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tarefa
      @tarefa = Tarefa.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tarefa_params
      params.require(:tarefa).permit(:titulo, :descricao, :user_id)
    end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tarefas_helper.rb
module TarefasHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Organizador De Tarefas</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <link rel="stylesheet" href="http://railsgirls.com/assets/bootstrap.css">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/lodash.js/3.2.0/lodash.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

    <script>
      $(document).ready(function(){
        $("#em_atraso").hide();
        $("#finalizadas").hide();
        $("#em_andamento-tab").click(function(){
          $("#em_andamento").show();
          $("#em_atraso").hide();
          $("#finalizadas").hide();
        });
        $("#em_atraso-tab").click(function(){
          $("#em_andamento").hide();
          $("#em_atraso").show();
          $("#finalizadas").hide();
        });
        $("#finalizadas-tab").click(function(){
          $("#em_andamento").hide();
          $("#em_atraso").hide();
          $("#finalizadas").show();
        });
      });
    </script>
  </head>

  <body>
    <p class="navbar-text pull-right">
      <% if user_signed_in? %>
        Logado como <strong><%= current_user.email %></strong>.
        <%= link_to 'Editar Perfil', edit_user_registration_path, :class => 'navbar-link' %> |
        <%= link_to "Sair", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
      <% end %>
    </p>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/tarefas/_form.html.erb
<%= form_with(model: tarefa, local: true) do |form| %>
  <% if tarefa.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tarefa.errors.count, "error") %> prohibited this tarefa from being saved:</h2>

      <ul>
      <% tarefa.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label "Título" %>
    <%= form.text_field :titulo %>
  </div>

  <div class="field">
    <%= form.label "Descrição" %>
    <%= form.text_area :descricao %>
  </div>

  <div class="field">
    <%= form.label "Prazo" %>
    <%= form.date_field("prazo") %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tarefas/edit.html.erb
<h1>Editando Tarefa</h1>

<%= render 'form', tarefa: @tarefa %>

<%= link_to 'Show', @tarefa %> |
<%= link_to 'Back', tarefas_path %>

app/views/tarefas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tarefas</h1>
<ul class="nav nav-tabs" id="myTab" role="tablist">
  <li class="nav-item">
    <a class="nav-link" id="em_andamento-tab" >Em Andamento <%= @tarefas_em_andamento.count(:id) %></a>
  </li>
  <li class="nav-item">
    <a class="nav-link" id="em_atraso-tab" >Em Atraso <%= @tarefas_em_atraso.count(:id) %></a>
  </li>
  <li class="nav-item">
    <a class="nav-link" id="finalizadas-tab" >Finalizadas <%= @tarefas_finalizadas.count(:id) %></a>
  </li>
</ul>
<div class="tab-content" id="myTabContent">
  <div id="finalizadas">
    <h3>Finalizadas</h3>
    <% if @tarefas_finalizadas.count(:id) > 0 %>
      <table class="table">
        <thead>
          <tr>
            <th>Título</th>
            <th>Descrição</th>
            <th>Data de finalização</th>
            <th colspan="3"></th>
          </tr>
        </thead>
      
        <tbody>
          <% @tarefas_finalizadas.each do |tarefa| %>
            <tr>
              <td><%= tarefa.titulo %></td>
              <td><%= tarefa.descricao %></td>
              <td><%= !tarefa.data_finalizado.nil? ? tarefa.prazo.strftime("%d/%m/%Y") : " " %></td>
              <td><%= link_to 'Mostrar', tarefa %></td>
              <td><%= link_to 'Editar', edit_tarefa_path(tarefa) %></td>
              <td><%= link_to 'Excluir', tarefa, method: :delete, data: { confirm: 'Tem certeza?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% else %>
      <p>Nenhuma tarefa finalizada</p>
    <% end %>
  </div>

  <div id="em_andamento" >
    <h3>Em Andamento</h3>
    <% if @tarefas_em_andamento.count(:id) > 0 %>
      <table class="table">
        <thead>
          <tr>
            <th>Título</th>
            <th>Descrição</th>
            <th>Prazo</th>
            <th colspan="3"></th>
          </tr>
        </thead>
      
        <tbody>
          <% @tarefas_em_andamento.each do |tarefa| %>
            <tr>
              <td><%= tarefa.titulo %></td>
              <td><%= tarefa.descricao %></td>
              <td><%= !tarefa.prazo.nil? ? tarefa.prazo.strftime("%d/%m/%Y") : " " %></td>
              <td><%= link_to 'Finalizar', controller: "tarefas", action: "finalizar", id: tarefa%></td>
              <td><%= link_to 'Mostrar', tarefa %></td>
              <td><%= link_to 'Editar', edit_tarefa_path(tarefa) %></td>
              <td><%= link_to 'Excluir', tarefa, method: :delete, data: { confirm: 'Tem certeza?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% else %>
      <p> Nenhuma tarefa em andamento</p>
    <% end %>
  </div>

  <div id="em_atraso" >
    <h3>Em Atraso</h3>
    <% if @tarefas_em_atraso.count(:id) > 0 %>
      <table class="table">
        <thead>
          <tr>
            <th>Título</th>
            <th>Descrição</th>
            <th>Prazo</th>
            <th colspan="3"></th>
          </tr>
        </thead>
      
        <tbody>
          <% @tarefas_em_atraso.each do |tarefa| %>
            <tr>
              <td><%= tarefa.titulo %></td>
              <td><%= tarefa.descricao %></td>
              <td><%= !tarefa.prazo.nil? ? tarefa.prazo.strftime("%d/%m/%Y") : " " %></td>
              <td><%= link_to 'Finalizar', controller: "tarefas", action: "finalizar", id: tarefa %></td>
              <td><%= link_to 'Mostrar', tarefa %></td>
              <td><%= link_to 'Editar', edit_tarefa_path(tarefa) %></td>
              <td><%= link_to 'Excluir', tarefa, method: :delete, data: { confirm: 'Tem certeza?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% else %>
      <p>Nenhuma tarefa em atraso </p>
    <% end %>
  </div>
</div>

<%= link_to 'Nova Tarefa', new_tarefa_path %>

app/views/tarefas/new.html.erb
<h1>Nova Tarefa</h1>

<%= render 'form', tarefa: @tarefa %>

<%= link_to 'Back', tarefas_path %>

app/views/tarefas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Título:</strong>
  <%= @tarefa.titulo %>
</p>

<p>
  <strong>Descrição:</strong>
  <%= @tarefa.descricao %>
</p>

<p>
  <strong>Prazo:</strong>
  <%= !@tarefa.prazo.nil? ? @tarefa.prazo.strftime("%d/%m/%Y") : " " %>
</p>

<%= link_to 'Editar', edit_tarefa_path(@tarefa) %> |
<%= link_to 'Voltar', tarefas_path %>